site_name: "LOTR: Renewed Extended Minecraft Mod Wiki"
site_url: https://maximuslotro.github.io/Extended-Wiki/

repo_url: https://github.com/maximuslotro/Extended-Wiki
repo_name: Extended-Wiki
edit_uri: edit/main/wiki/docs/

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  language: en
  logo: icons/logo.png
  favicon: icons/logo.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    #- navigation.sections
    #- navigation.expand
    #- navigation.path
    #- navigation.top
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    tag:


nav:
    - Home: index.md
    - Blocks: 
        - All Blocks: blocks/blocks.md
        - Wood Types:
            - Banana: blocks/banana_wood.md
            - Chestnut: blocks/chestnut_wood.md
            - Plum: blocks/plum_wood.md
            - Willow: blocks/willow_wood.md
        - Stones:
            - Dirt: blocks/dirt.md
            - Scorched Stone: blocks/scorched_stone.md
            - Drystone: blocks/drystone.md
            - Obsidian: blocks/obsidian.md
        - Ultiliy Blocks:
            - Stone Grinder: blocks/stone_grinder.md
            - Crucible: blocks/crucible.md
        - Food Blocks:
            - Cheese Wheel: blocks/cheese_wheel.md
            - Adged Cheese Wheel: blocks/adged_cheese_wheel.md


extra:
  tags:
    Blocks: blocks
plugins:
  - tags
  - search
  - pagelist
  - htmlproofer
extra_css:
    - stylesheets/custom.css
    - stylesheets/extra.css