site_name: "LOTR: Renewed Extended Minecraft Mod Wiki"
site_url: https://lotrextendedteam.github.io/Extended-Wiki/
repo_url: https://github.com/LotrExtendedTeam/Extended-Wiki
repo_name: Extended-Wiki
edit_uri: edit/main/wiki/docs/

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  language: en
  logo: icons/logo.png
  favicon: icons/logo.png
  custom_dir: overrides
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to darker mode

    # Palette toggle for darker mode
    - media: "(prefers-color-scheme: dark)"
      scheme: pitch
      primary: indigo
      toggle:
        icon: material/brightness-3
        name: Switch to midnight mode

    # Palette toggle for midnight mode
    - scheme: midnight
      primary: indigo
      toggle:
        icon: material/brightness-1
        name: Switch to light mode
  features:
    - navigation.tabs #add top navigation bar with main catagories
    #- navigation.tracking # updates the URL bar with the current selected TOC section
    - navigation.top #adds a button to jump to top of page
    - navigation.path # does not do anything right now as its a sponser only option currently
    #- navigation.indexes #hide top level navigation duplication
    - content.action.edit #add edit button on upper right corner
    - toc.integrate #toc is rendered as part of the navigation sidebar
    - navigation.prune # prune bloat navigation
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    tag:


nav:
    - Home:
        - Home: index.md
    - Blocks:
        - All Blocks: blocks.md
        - Wood Types:
            - Banana: banana_wood.md
            - Chestnut: chestnut_wood.md
            - Plum: plum_wood.md
            - Willow: willow_wood.md
        - Stones:
            - Dirt: dirt.md
            - Scorched Stone: scorched_stone.md
            - Drystone: drystone.md
            - Obsidian: obsidian.md
        - Ultiliy Blocks:
            - Stone Grinder: stone_grinder.md
            - Crucible: crucible.md
        - Food Blocks:
            - Cheese Wheel: cheese_wheel.md
            - Adged Cheese Wheel: adged_cheese_wheel.md
    - Items:
        - All Items: items.md
        - Food:
            - Hobbit Pancake: hobbit_pancake.md
    - Misc:
        - Updates: updates.md

hooks:
  - docs/plugins/git_history.py
  - docs/plugins/infobox_processor.py
plugins:
  - tags:
      tags_allowed:
        - Blocks
        - Items
  - search:
  - htmlproofer:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false
  - social:
       enabled: !ENV [CI, false]
       cards: true
       cards_layout_options:
        background_color: "#998f65"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.snippets
  - toc:
      toc_depth: 3

extra_css:
    - stylesheets/custom.css
    - stylesheets/extra.css
    - stylesheets/history.css
    - stylesheets/infobox.css

extra_javascript:
    - javascripts/history.js
