site_name: "LOTR: Renewed Extended Minecraft Mod Wiki"
site_url: https://lotrextendedteam.github.io/Extended-Wiki/
repo_url: https://github.com/LotrExtendedTeam/Extended-Wiki
repo_name: Extended-Wiki
edit_uri: edit/main/wiki/docs/
copyright: |
  &copy; 2025 maximuslotro, LotrExtendedTeam

validation:
  links:
    absolute_links: ignore
    anchors: warn
    unrecognized_links: warn

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  language: en
  logo: icons/logo.png
  favicon: icons/logo.png
  custom_dir: overrides
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to darker mode

    # Palette toggle for darker mode
    - media: "(prefers-color-scheme: dark)"
      scheme: pitch
      primary: indigo
      toggle:
        icon: material/brightness-3
        name: Switch to midnight mode

    # Palette toggle for midnight mode
    - scheme: midnight
      primary: indigo
      toggle:
        icon: material/brightness-1
        name: Switch to light mode
  features:
    - navigation.tabs #add top navigation bar with main categories
    #- navigation.tracking # updates the URL bar with the current selected TOC section
    - navigation.top #adds a button to jump to top of page
    - navigation.path # does not do anything right now as its a sponsor only option currently
    #- navigation.indexes #hide top level navigation duplication
    - toc.integrate #toc is rendered as part of the navigation sidebar
    #- navigation.prune # prune bloat navigation
    - content.action.edit #add edit button on upper right corner
    - content.code.copy #render a button on the right side of code to copy
    - content.code.select #render a button on the right side of code to select
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    tag:

hooks:
  - docs/hooks/git_history.py
  - docs/hooks/infobox_processor.py
  - docs/hooks/flatten_urls.py
  - docs/hooks/gif_maker.py

plugins:
  - search
  - alias
  - tags:
      tags_allowed:
        - Blocks
        - Items
        - Entities
        - Factions
        - Biomes
  - literate-nav:
      nav_file: nav.txt
  #- htmlproofer      (ignored for now as it fails file check with our custom link re-mapping system)
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: auto
       height: auto
       zoomable: true
       draggable: true
       auto_caption: true
       caption_position: bottom
       background: 74b9ff
       shadow: false
       manual: false
  - social:
       enabled: !ENV [CI, false]
       cards: true
       cards_layout_options:
        background_color: "#998f65"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.blocks.caption
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 3

extra_css:
    - stylesheets/custom.css
    - stylesheets/themes.css
    - stylesheets/history.css
    - stylesheets/infobox.css
    - stylesheets/flex-row.css
    - stylesheets/glightbox.css
    - stylesheets/topbar-layout.css

extra_javascript:
    - javascripts/history.js
    - javascripts/glightbox.js
