site_name: "LOTR: Renewed Extended Minecraft Mod Wiki"
site_url: https://maximuslotro.github.io/Extended-Wiki/

repo_url: https://github.com/maximuslotro/Extended-Wiki
repo_name: Extended-Wiki
edit_uri: edit/main/wiki/docs/

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  language: en
  logo: icons/logo.png
  favicon: icons/logo.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    #- navigation.sections
    #- navigation.expand
    #- navigation.path
    - navigation.top
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    tag:


nav:
    - Home: index.md
    - Blocks: 
        - All Blocks: blocks.md
        - Wood Types: 
            - Banana: banana_wood.md
            - Chestnut: chestnut_wood.md
            - Plum: plum_wood.md
            - Willow: willow_wood.md
        - Stones:
            - Dirt: dirt.md
            - Scorched Stone: scorched_stone.md
            - Drystone: drystone.md
            - Obsidian: obsidian.md
        - Ultiliy Blocks:
            - Stone Grinder: stone_grinder.md
            - Crucible: crucible.md
        - Food Blocks:
            - Cheese Wheel: cheese_wheel.md
            - Adged Cheese Wheel: adged_cheese_wheel.md
    - Items: 
        - All Items: items.md
        - Food:
            - Hobbit Pancake: hobbit_pancake.md

plugins:
  - tags:
      tags_allowed:
        - Blocks
        - Items
  - search:
  - htmlproofer:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
extra_css:
    - stylesheets/custom.css
    - stylesheets/extra.css